# Generated by Django 4.0.4 on 2022-05-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookTicketModel',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_from', models.CharField(max_length=100)),
                ('book_to', models.CharField(max_length=100)),
                ('no_of_adults', models.IntegerField()),
                ('no_of_children', models.IntegerField()),
                ('train_number', models.IntegerField()),
                ('train_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
            options={
                'db_table': 'booking_details',
            },
        ),
        migrations.CreateModel(
            name='UserRegModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Enter First name', max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(help_text='Enter email', max_length=100)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='UserComplaintModel',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.TextField()),
                ('train', models.ForeignKey(db_column='train', on_delete=django.db.models.deletion.CASCADE, to='userapp.userbookticketmodel')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='userapp.userregmodel')),
            ],
            options={
                'db_table': 'user_complaints',
            },
        ),
        migrations.AddField(
            model_name='userbookticketmodel',
            name='user_details',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='userapp.userregmodel'),
        ),
    ]
