# Generated by Django 4.0.4 on 2022-05-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookticketmodel',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userbookticketmodel',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
