# Generated by Django 4.0.4 on 2022-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_userbookticketmodel_date_userbookticketmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookticketmodel',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userbookticketmodel',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
