# Generated by Django 4.0.4 on 2022-05-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_usercomplaintmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomplaintmodel',
            name='user',
        ),
    ]
